feat(widgets): Add support for tileset sources and local widget calculations
CartoDB/carto-api-client pull request #50
Opened 2024-12-31 00:22 UTC by donmccurdy

2025-02-07 10:05 UTC, padawannn requested changes
Great job @donmccurdy. Some small comments, can you take a look?

2025-02-07 10:05 UTC, padawannn commented on package.json
> +  "version": "0.5.0-alpha.2",
Don't forget to undo this change before merge

2025-02-07 10:05 UTC, padawannn commented on src/filters/tileFeatures.ts
> +  // is omitted? Why not make the parameter required, or return the full input?
Agree make it required, please

2025-02-07 10:05 UTC, padawannn commented on src/filters/index.ts
> +export * from './Filter.js';
Should we export the `ts` files instead of `js` files? I mean
```
export * from './Filter.ts';
```
instead of
```
export * from './Filter.js';
```

I've notice other exports like this in other places like https://github.com/CartoDB/carto-api-client/blob/main/src/index.ts#L1

2025-02-07 10:05 UTC, padawannn commented on src/index.ts
> +export * from './filters/index.js';
Same comment, should not be 
```
export * from './filters/index.ts'
```

2025-02-07 10:05 UTC, padawannn commented on src/operations/groupBy.ts
> +import {aggregationFunctions, aggregate} from './aggregation.js';
import from `./aggregation.ts`

2025-02-07 18:15 UTC, donmccurdy commented on package.json
> +  "version": "0.5.0-alpha.2",
This is safe to merge – if we later do `yarn version patch`, yarn will look at the `package.json#stableVersion` entry below and automatically update to 0.4.6 and not 0.5.1, so we are able to increment either the 'alpha' or the 'latest' release safely.

If there are any other worries though, I'm happy to remove it!

2025-02-07 18:21 UTC, donmccurdy commented on src/filters/index.ts
> +export * from './Filter.js';
We can't do `.ts` I think, the build process would have to rename the imports in `.d.ts` files to `.js` at build time, and TypeScript has for a very long time been against allowing that:

- https://github.com/microsoft/TypeScript/issues/49462

The filenames are supposed to be paths that can be resolved _after_ TypeScript compilation, so we are stuck with either `./Filter` or `./Filter.js`. Currently the codebase has a mix of both ... so that is not great, I would like to clean it up to be consistent, I'll do that in a new PR. 😅

While I'm happy with either in an app like Builder, I think that for libraries we may need to use `.js`, because that's what should appear in the published `.d.ts` files. It's required for customers using certain configurations, particularly `moduleResolution: 'nodenext'`. I've had this feedback in some of my personal repositories in the past, discussion here:

- https://github.com/donmccurdy/glTF-Transform/pull/827

2025-02-07 18:22 UTC, donmccurdy commented on src/index.ts
> +export * from './filters/index.js';
See above – I think it's correct but will start a new PR to make this consistent at least!

2025-02-07 18:22 UTC, donmccurdy commented on src/operations/groupBy.ts
> +import {aggregationFunctions, aggregate} from './aggregation.js';
See above – I think it's correct but will start a new PR to make this consistent at least!

2025-02-07 18:25 UTC, donmccurdy commented on src/filters/index.ts
> +export * from './Filter.js';
For now I've opened a new issue to track this:

- https://github.com/CartoDB/carto-api-client/issues/99

I'll wait to make the changes until after this PR and the raster PR are merged, so we don't have a bunch of merge conflicts.

2025-02-10 08:52 UTC, padawannn commented on package.json
> +  "version": "0.5.0-alpha.2",
ok, thx!

2025-02-10 09:02 UTC, padawannn commented on src/filters/index.ts
> +export * from './Filter.js';
@donmccurdy, why don't we export the file without the extension as Deck.gl does? https://github.com/visgl/deck.gl/blob/master/modules/core/src/index.ts#L90

2025-02-10 09:03 UTC, padawannn approved these changes
Thank you for your comments.  I've approved the PR but please check this comment https://github.com/CartoDB/carto-api-client/pull/50#discussion_r1948660036

2025-02-10 21:31 UTC, donmccurdy commented on src/filters/index.ts
> +export * from './Filter.js';
So deck.gl is using `... from './Foo'` in source files, but they've written a special build step that adds the `.js` extension to the generated `.d.ts` files:

https://github.com/uber-web/ocular/blob/6d84ec50d8c80dc2cf361e818e9edb35f597042a/modules/dev-tools/src/ts-plugins/ts-transform-append-extension/index.ts

Added in:

- https://github.com/uber-web/ocular/pull/446

Admittedly putting the `.js` extension in source code is weird/ugly... but without customizing the build process I don't know of another way to solve that problem for customers. Another option would be to bundle the `.d.ts` files into one file, so there are no imports in the output, but that will complicate the build step and I haven't found a build setup that I trust for that yet. 😕

2025-02-10 21:37 UTC, merged